# Generated by Django 5.2 on 2025-05-14 16:14

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rede_social', '0003_invite'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invite',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
